-- Filtros usando duas tabelas diferentes
SELECT VENDAS.ID_VENDEDOR, VENDEDORES.NOME_VENDEDOR, SUM(VENDAS.QTD_VENDIDA) 
	FROM VENDAS, VENDEDORES
		WHERE VENDAS.ID_VENDEDOR = VENDEDORES.ID_VENDEDOR
        GROUP BY VENDAS.ID_VENDEDOR;
        
-- INNER JOIN
SELECT VENDAS.ID_VENDEDOR, VENDEDORES.NOME_VENDEDOR, SUM(VENDAS.QTD_VENDIDA) 
	FROM VENDAS INNER JOIN VENDEDORES
		ON VENDAS.ID_VENDEDOR = VENDEDORES.ID_VENDEDOR
        GROUP BY VENDAS.ID_VENDEDOR;
        
/*
Link para artigo sobre agregação e métricas:
https://www.alura.com.br/artigos/trabalhando-funcoes-de-agregacao?_gl=1*1u6r10r*_ga*Njk0NzYzNTQxLjE2NzQ5MjI2MTY.*_ga_59FP0KYKSM*MTY5MDM5NTY2Mi4xMjUuMS4xNjkwNDAzNzg3LjAuMC4w*_fplc*NkpQdVUwcGVyaEhQbWdKcjN2ZTlvdUZvYXpwVFZZT1ZJelhmcjlXZTNHdUtFN09ReE9xWDJZM1hVRFlmZ0lWQkZhalFOJTJCaU1hQyUyQjNXRUpOZXNMMW1pcFhrSklvckU0TEpEQ2diODBDVVMxb1Q1YUhwQ29WeHhqbGRvMTNLdyUzRCUzRA..
*/

-- LEFT JOIN
SELECT LIVROS.NOME_LIVRO,
	   VENDAS.QTD_VENDIDA
	FROM LIVROS LEFT JOIN VENDAS
		ON LIVROS.ID_LIVRO = VENDAS.ID_LIVRO;

-- RIGHT JOIN
SELECT LIVROS.NOME_LIVRO,
	   VENDAS.ID_LIVRO,
	   VENDAS.QTD_VENDIDA
	FROM LIVROS RIGHT JOIN VENDAS
		ON LIVROS.ID_LIVRO = VENDAS.ID_LIVRO;
		
/*
Artigo sobre JOIN

https://www.alura.com.br/artigos/join-em-sql?_gl=1*1guk00a*_ga*Njk0NzYzNTQxLjE2NzQ5MjI2MTY.*_ga_59FP0KYKSM*MTY5MDM5NTY2Mi4xMjUuMS4xNjkwNDA0Mjg1LjAuMC4w*_fplc*OGpOek91dk12JTJCUWNTdmdaUTNNTER0UWp0dnhpYlk2VmJ5cmMwNnF4JTJCJTJGOGFGTnFtTlN6JTJGcEt1eFBJMnlyZWI5bTFicnBTalRsZXFnOXFBaGRLSXpsZU1nakgzWG1rREhMdVRpV0txeVlncWxGazJyUDdIRkRuaE5iVDdkUFElM0QlM0Q.
*/





